version: '3'
services: 
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile.dev
    command: python3 server.py
    volumes:
        - ./app/backend:/app
    environment:
        - FLASK_ENV=development
    ports:
        - 5000:5000
  frontend:
    build: 
      context: ./app/frontend
      dockerfile: Dockerfile.dev
    command: npm run serve
    volumes:
        - ./app/frontend:/app
    ports:
        - 3035:3035